openapi: 3.1.0
info:
  version: 1.0.0
  title: Harmoniq API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Harmoniq app
tags:
  - name: Articles
    description: Operations about articles.
  - name: Auth
    description: Auth operations.
  - name: Authors
    description: Operations about authors.
servers:
  # - url: http://localhost:3000
  - url: https://harmoniq-backend-qo0h.onrender.com
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml

  /articles:
    post:
      $ref: ../swagger/paths/articles/post.yaml
    get:
      $ref: ../swagger/paths/articles/get.yaml
  /articles/{id}:
    get:
      $ref: ../swagger/paths/articles/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/articles/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/articles/{id}/delete.yaml

  /authors:
    get:
      $ref: ../swagger/paths/users/getAllUsers.yaml
  /authors/{id}:
    get:
      $ref: ../swagger/paths/users/{id}/getUsersById.yaml
  /authors/saved-articles:
    get:
      $ref: ../swagger/paths/users/{id}/getSavedArticlesById.yaml
  /authors/saved-articles/{id}:
    patch:
      $ref: ../swagger/paths/users/patchSavedArticlesById.yaml
    delete:
      $ref: ../swagger/paths/users/deleteSavedArticlesById.yaml
  /authors/{id}/articles:
    get:
      $ref: ../swagger/paths/users/getArticlesById.yaml
  /user/photo:
    post:
      $ref: ../swagger/paths/users/postUserPhoto.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
