openapi: 3.1.0
info:
  version: 1.0.0
  title: Harmoniq API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Harmoniq app
tags:
  - name: Articles
    description: Operations about articles.
  - name: Auth
    description: Auth operations.
servers:
  # - url: http://localhost:3000
  - url: https://harmoniq-backend-qo0h.onrender.com
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/send-reset-email.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/reset-pwd.yaml

  /articles:
    post:
      $ref: ../swagger/paths/articles/post.yaml
    get:
      $ref: ../swagger/paths/articles/get.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/articles/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/articles/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/articles/{id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
